### PR TITLE
Add missing "to_dict()" function for converting JSONItem_MTC into an Dictionary, change from XOJO XML to normal XOJO Code

### PR DESCRIPTION
**Pull request by dhaeb**
Hey Kem, 

some easy changes for making the project more applicable. We only changed to XOJO_CODE files to make it easiser to track the changes. I also added a **"Function toDict() As Dictionary"** function because we needed that regularly. 

Let us know what we could improve to merge our changes with yours!

Best, 

Dan

### CODE REVIEW

**Comment by ktekinay** [comment]
I appreciate the contribution but I won't be merging this. 

The files are in XML format intentionally so they can be used as external classes in my projects. 

You can already convert to Dictionary by simple assignment. `var d as Dictionary = myJSONItemMTC`. You can do the same with to a Variant array.

**Comment by dhaeb** [comment]
Hey Kem,
thanks for the reply.
> The files are in XML format intentionally so they can be used as external classes in my projects. 

We also use it as "external classes" in XOJO with git submodules and XOJO_CODE files. The problem with the XML:
1) it's not readable without the XOJO IDE
2) tracking changes can be very hard using VCS
So I don't understand why your files needs to be XML to use them in multiple projects. 

> You can already convert to Dictionary by simple assignment. var d as Dictionary = myJSONItemMTC. You can do the same with to a Variant array.

Well as you can see be my contribution, I wasn't aware of this implicit conversion. It should be more explicit, this is much more readable and we are talking about 10 lines more code here. 

Finally, if you shy away from merging contributions, we won't develop on the same project, therefore never benefit from each others work. This is one of the major drawbacks of XOJO in gerneral. There is no open source mindset. 
I highly recommend merging this little change rather than always stay in our ivory towers. In the XOJOUnit project, we took it over internally and created interesting addiotions which some XOJO users never will benefit from because we did not manage to collaborate. I don't want this waste of human engineering power and lifetime for others to happen. 

At least, make clear to me what we have to change to have a mergable contribution. Thanks

Best, 

Dan

**Comment by ktekinay** [comment]
> At least, make clear to me what we have to change to have a mergable contribution.

1. Do not convert from XML.
2. Leverage the existing Operator_Convert to convert to a Dictionary.
3. Add a ToArray function that does the same.
3. Initial-cap the function name.
4. Merge against the develop branch rather than the master branch.

**Comment by dhaeb** [comment]
Can you explain to me why you need the XML format please? What benefits offers it over the XOJO_CODE?

**Comment by ktekinay** [comment]
I use the XML file as an external in other projects and changing it now would break those. Only binary or XML format files can be used as externals in projects.

**Comment by dhaeb** [comment]
> Only binary or XML format files can be used as externals in projects.

Can you provide more information (docs etc?) to this fact? I never understood why there is a XOJO_XML format anyways. The point is that those files are really not helpful for VCS like git, therefore we changed to XOJO_CODE. 
I really appreciate your help in understanding the XOJO realm. I never used a language before where it's a mess putting code in git. We need to collaborate to create successful software. So I always strive for VCS first.

**Comment by ktekinay** [comment]
I can't find it in the docs right now after taking a quick look, but do this: in a project, right-click on a class and you will see something like "Make External". That will bring up a Save dialog that will let you save the class as binary or XML. After that, the class becomes external to the project.

**Comment by dhaeb** [comment]
Ok. What benefits offers an "External Class" over an non external?

**Pull request closed without merging**
